# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x06protos\"1\n\rStatusRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"!\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\x0bTaskRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\x05\x12\x0c\n\x04task\x18\x02 \x01(\t\"\x1f\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x86\x01\n\x0c\x41gentService\x12=\n\x0cUpdateStatus\x12\x15.protos.StatusRequest\x1a\x16.protos.StatusResponse\x12\x37\n\nSubmitTask\x12\x13.protos.TaskRequest\x1a\x14.protos.TaskResponseB\tZ\x07protos/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007protos/'
  _globals['_STATUSREQUEST']._serialized_start=23
  _globals['_STATUSREQUEST']._serialized_end=72
  _globals['_STATUSRESPONSE']._serialized_start=74
  _globals['_STATUSRESPONSE']._serialized_end=107
  _globals['_TASKREQUEST']._serialized_start=109
  _globals['_TASKREQUEST']._serialized_end=154
  _globals['_TASKRESPONSE']._serialized_start=156
  _globals['_TASKRESPONSE']._serialized_end=187
  _globals['_AGENTSERVICE']._serialized_start=190
  _globals['_AGENTSERVICE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
